<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="concretemodel" nsURI="http://concretemodel" nsPrefix="concretemodel">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactoryConcrete">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listProjects" upperBound="-1"
        eType="#//ProjectAdj" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectAdj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstClassDiagramAdj" upperBound="-1"
        eType="#//ClassDiagramAdj" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstAttributeTypeConcreteAdj"
        upperBound="-1" eType="#//AttributeTypeConcreteAdj" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDiagramAdj">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstPackageConcreteAdj"
        upperBound="-1" eType="#//PackageConcreteAdj" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstRelationship" upperBound="-1"
        eType="#//RelationshipAdj" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstClassConcreteAdj" upperBound="-1"
        eType="#//ClassConcreteAdj" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageConcreteAdj">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipAdj" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicityTargetClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicitySourceClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classSource" eType="#//ClassConcreteAdj"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classTarget" eType="#//ClassConcreteAdj"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentSdj" eSuperTypes="#//RelationshipAdj">
    <eAnnotations source="gmf.link">
      <details key="source" value="classSource"/>
      <details key="target" value="classTarget"/>
      <details key="source.decoration" value="none"/>
      <details key="target.decoration" value="filledrhomb"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
      <details key="color" value="0,0,0"/>
      <details key="target.decorationSize" value="16"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SharingAdj" eSuperTypes="#//RelationshipAdj">
    <eAnnotations source="gmf.link">
      <details key="source" value="classSource"/>
      <details key="target" value="classTarget"/>
      <details key="source.decoration" value="none"/>
      <details key="target.decoration" value="rhomb"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
      <details key="color" value="0,0,0"/>
      <details key="target.decorationSize" value="16"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationAdj" eSuperTypes="#//RelationshipAdj">
    <eAnnotations source="gmf.link">
      <details key="source" value="classSource"/>
      <details key="target" value="classTarget"/>
      <details key="source.decoration" value="none"/>
      <details key="target.decoration" value="none"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralizationAdj" eSuperTypes="#//RelationshipAdj">
    <eAnnotations source="gmf.link">
      <details key="source" value="classSource"/>
      <details key="target" value="classTarget"/>
      <details key="source.decoration" value="none"/>
      <details key="target.decoration" value="arrow"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
      <details key="color" value="0,0,0"/>
      <details key="target.decorationSize" value="16"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassConcreteAdj">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="color" value="255,255,128"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accesModifierClass" eType="#//AccessModifierClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipeClass" eType="#//TypeClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstAttributeConcreteAdj"
        upperBound="-1" eType="#//AttributeConcreteAdj" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
        <details key="collapsible" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstMethodConcreteAdj" upperBound="-1"
        eType="#//MethodConcreteAdj" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
        <details key="collapsible" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodConcreteAdj">
    <eAnnotations source="gmf.node">
      <details key="label" value="methodName"/>
      <details key="color" value="255,255,128"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessModifier" eType="#//AccessModifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstParameterConcreteAdj"
        upperBound="-1" eType="#//ParameterConcreteAdj" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterConcreteAdj">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="color" value="255,255,128"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AttributeTypeConcreteAdj"
        eType="#//AttributeTypeConcreteAdj"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeTypeConcreteAdj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParameterConcreteAdj" upperBound="-1"
        eType="#//ParameterConcreteAdj" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstAttributeConcreteAdj"
        upperBound="-1" eType="#//AttributeConcreteAdj" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeConcreteAdj">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="color" value="255,255,128"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessModifier" eType="#//AccessModifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeTypeConcreteAdj"
        eType="#//AttributeTypeConcreteAdj"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessModifier">
    <eLiterals name="public" value="1"/>
    <eLiterals name="private" value="2"/>
    <eLiterals name="protected" value="3"/>
    <eLiterals name="static" value="4"/>
    <eLiterals name="internal" value="5"/>
    <eLiterals name="protected_internal" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessModifierClass">
    <eLiterals name="public" value="1"/>
    <eLiterals name="internal" value="2"/>
    <eLiterals name="protected" value="3"/>
    <eLiterals name="protected_internal" value="4"/>
    <eLiterals name="private" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeClass">
    <eLiterals name="regular" value="1"/>
    <eLiterals name="abstrac" value="2"/>
    <eLiterals name="sealed" value="3"/>
    <eLiterals name="static" value="4"/>
    <eLiterals name="generic" value="5"/>
  </eClassifiers>
</ecore:EPackage>
