<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dslrelational" nsURI="http://dslrelational" nsPrefix="dslrelational">
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactoryRelational">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstDataProject" upperBound="-1"
        eType="#//DataProject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataProject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstTable" upperBound="-1"
        eType="#//Table" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstFunction" upperBound="-1"
        eType="#//Function" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstTrigger" upperBound="-1"
        eType="#//Trigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBySchema" eType="#//Schema"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstTrigger" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstColumn" upperBound="-1"
        eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstPrimaryKey" upperBound="-1"
        eType="#//PrimaryKey" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstForeignKey" upperBound="-1"
        eType="#//ForeignKey" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByTable" eType="#//Table"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstPrimaryKey" upperBound="-1"
        eType="#//PrimaryKey" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByTable" eType="#//Table"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstForeignKey" upperBound="-1"
        eType="#//ForeignKey" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theColumn" eType="#//Column"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByTable" eType="#//Table"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thePrimaryKey" eType="#//PrimaryKey"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statementTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBySchema" eType="#//Schema"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theTable" eType="#//Table"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBySchema" eType="#//Schema"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstParameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByFunction" eType="#//Function"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
